install.packages("ISLR")
library(ISLR)
attach(Wage)
View(Wage)
fit=lm(wage~poly(age,4), data=Wage) #fourth degree polynomial in age
coef(summary(fit))
coef(fit)
fit2=lm(wage~poly(age,4,raw=T), data=Wage)
coef(summary(fit2))
coef(fit2)
fit2a=lm(wage~age+I(age^2)+I(age^3)+I(age^4), data=Wage)
coef(fit2a)
agelims=range(age)
age.grid=seq(from=agelims[1], to=agelims[2])
preds=predict(fit,newdata=list(age=age.grid),se=TRUE)
se.bands=cbind(preds$se.fit,preds$fit-2*preds$se.fit)
par(mfrow=c(1,2),mar=c(4.5,4.5,1,1),oma=c(0,0,4,0))

fit=glm(I(wage>250)~poly(age,4),data=Wage,family=binomial)
preds=predict(fit,newdata=list(age=age.grid),se=T)
pfit=exp(preds$fit)/(1+exp(preds$fit))
se.bands.logit=cbind(preds$fit+2*preds$se.ft,preds$fit-2*preds$se.fit)
se.bands=exp(se.bands.logit)/(1+exp(se.bands.logit))
plot(age,I(wage>250),xlim=agelims,type="n",ylim=c(0,.2))
points(jitter(age),I((wage>250)/5),cex=.5,pch="|",col=" darkgrey ")
lines(age.grid,pfit,lwd=2,col=" blue")

install.packages("gam")
gam1=lm(wage~s(year,4)+ns(age,5)+education,data=Wage)
gam.m3=gam(wage~s(year,4)+s(age,5)+education,data=Wage)
par(mfrow=c(1,3))
plot(gam.m3,se=TRUE,col="blue")
